spring.application.name=steam-web

spring.datasource.url=jdbc:mysql://localhost:3306/steam?serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=11080525Yuri484485@@

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.thymeleaf.cache=false

spring.sql.init.mode=never

server.address=0.0.0.0
server.port=8080
